### ISSUE TITLE
ERROR in ./node_modules/bootstrap-loader/lib/bootstrap.loader.js!./node_modules/bootstrap-loader/no-op.js Module build failed: Error: Cannot find module 

### ISSUE THREAD

**Issue by SACHINBN** [shakacode/bootstrap-loader#368]
Hi ,
I am getting below error after build without changing code
ERROR in ./node_modules/bootstrap-loader/lib/bootstrap.loader.js!./node_modules/bootstrap-loader/no-op.js
Module build failed: Error: Cannot find module '/home/jenkins/workspace/CDLCore_POC/UploadApp/node_modules/bootstrap-sass/package.json/package.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at exports.default (/home/jenkins/workspace/CDLCore_POC/UploadApp/node_modules/bootstrap-loader/lib/utils/checkBootstrapVersion.js:8:20)
    at Object.module.exports.pitch (/home/jenkins/workspace/CDLCore_POC/UploadApp/node_modules/bootstrap-loader/lib/bootstrap.loader.js:159:65)
 @ ./node_modules/bootstrap-loader/loader.js 2:17-61
 @ ./src/uploadApp/main.ts
 @ multi ./src/uploadApp/main.ts

I am using following below version -
1.Node - 8.5
2.  "bootstrap": "4.3.1",
 3. "bootstrap-loader": "2.2.0",
 4. "bootstrap-sass": "3.4.1",
5.angular:4.1
6.Typescript:3.6.3

Please help me to resolve

**Comment by ANjaa** [comment]
We're having the exact same problem with 2.1.0 (and resolve 1.4.0).

**Comment by SACHINBN** [comment]
I am not getting same error in my local build but jenkin machine I am getting

**Comment by ANjaa** [comment]
Our resolve version was 1.4.0, but bootstrap-loader (both 2.1.0 and 2.2.0) fetched the newest release, which was 4 days ago, where they updated to resolve 1.13.0.

When we updated package lock to override bootstrap-loader from ^ notation to 1.12.0 specifically, the issue was solved.

**Comment by medicalwei** [comment]
This is caused by #359

**Comment by justin808** [comment]
Let's close b/c we have #359.
